[development]
address = "localhost"
port = 8080
workers = 2
# debug normal critical
log = "normal"
# head -c 32 /dev/urandom | base64
secret_key = "g7+3735w/Vby1qq1Y92/s20CHecbYN/2fvHc49nq5i0="
limits = { forms = 32768 }
template_dir = "themes/moon/views"
